### ISSUE TITLE
[Page] permission issue when trying to read template and page policy

### ISSUE THREAD

**Issue by honstar** [adobe/aem-core-wcm-components#276]
## Bug Report

**Current Behavior**
Given an editable template with a page policy set that points to one or more clientlib categories. A page based on that template renders fine with all expected CSS styles on the authoring instance.

However, once that page is replicated across to a publish instance and subsequently requested, the clientlibs defined via the template's page policy are not loaded, hence the design of the page is broken.

This is caused by lack of permissions to read both a page's `Template` and `ContentPolicyStyle` using `anonymous` on publish.

**Expected behavior/code**
All clientlibs should be loaded on publish instances as well via `anonymous`.

**Environment**
- AEM version and patch level: AEM 6.4 + SP 1 (6.4.1.0)
- Core Components version: 2.0.4
- JRE version: 1.8

**Possible Solution**
To overcome permission issues while accessing a page's `Template` and `ContentPolicyStyle` objects, a separate service to read these could be added. That service would use a specific service user mapped against a system user that provides read access to the following:
- `/conf/*/templates`
- `/conf/*/policies`

Alternatively, granting read access could theoretically be delegated to the consuming project. However, this would require explicit documentation and kind of goes against the OOTB functionality that the Core Components Page brings to the table.

**Comment by kwin** [comment]
This is usually solved with the application leveraging the core wcm components, compare with we-retail which set's those rights with their "ui.content" package in https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/blob/master/ui.content/src/main/content/jcr_root/conf/we-retail/settings/wcm/policies/_rep_policy.xml.

**Comment by honstar** [comment]
I'm fine with applying proper permissions on the consuming side. Is this documented anywhere that custom permissions need to be set in case page policies are used in editable templates?

**Comment by gabrielwalt** [comment]
This has been documented here:
https://helpx.adobe.com/experience-manager/6-4/sites/developing/using/page-templates-editable.html#main-pars_title_1739798510

In case some information is still missing, please reopen.

**Comment by honstar** [comment]
Thanks for the update @gabrielwalt 👍
