### ISSUE TITLE
Couple of issues with the core Search component

### ISSUE THREAD

**Issue by tim-merrillcorp** [adobe/aem-core-wcm-components#426]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior and your setup; if applicable, proxy component pattern and component version.

**Expected behavior/code**

**Environment**
- AEM version and patch level (e.g. AEM 6.3 SP1 CFP2)
- Core Components version (e.g. 2.0.4)
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`)

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by richardhand** [comment]
@tim-merrillcorp, thanks for your report, I moved the second issue to #427.

As the results are provided on the fly, it seems like they're not run through the default link checker and therefore require handling to ensure they are mapped correctly.

**Comment by gabrielwalt** [comment]
This should be fixed by #713.

**Comment by kwin** [comment]
As #713 might take some time, why not simply calling `RR.map(...)` on the JSON value in the mean time? Would you accept a PR for that?

**Comment by kwin** [comment]
@vladbailescu WDYT about a fix which would just call RR.map  on https://github.com/adobe/aem-core-wcm-components/blob/345377e9701a6724abc8ddf5a1fc5c3ade85f406/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/Utils.java#L61?

**Comment by vladbailescu** [comment]
@kwin, it would require some testcases to make sure it does not break stuff, but could be a solution. We would appreciate some help here, especially with the testcases.

**Comment by kwin** [comment]
@vladbailescu Isn't this solved in 2.16.0 (https://github.com/adobe/aem-core-wcm-components/blob/2e055f9d4a1777155229dae22d948ce7ec095a42/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/servlets/SearchResultServlet.java#L305)?

**Comment by olenaslyshkova** [comment]
As I can see the issue is still reproducible on the core component version 2.17.10.
Can be also seen in the https://wknd.site/us/en.html site (search for "magazine") which uses the  2.16.4 core components version.

**Comment by cpiosecny** [comment]
The results in _SearchResultServlet_ are getting wrapped in _PageListItemImpl_ which is calling _LinkManager_ to build a Link.
The _LinkImpl_ created in _LinkBuilderImpl_ sets the url field to the sanitized "URL", which just is the sanitized path. This gets exposed via LinkImpl#getURL to the _PageListItemImpl#getURL_  and clearly is not a URL

**Comment by TitusRobyK** [comment]
Any traction for this issue ?
